# Generated by Django 4.2.4 on 2023-10-23 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model_users',
            name='img',
        ),
        migrations.AddField(
            model_name='model_users',
            name='url_img',
            field=models.URLField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
