# Generated by Django 4.2.4 on 2023-08-23 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0002_alter_model_users_managers_model_users_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='model_users',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AddField(
            model_name='model_users',
            name='img',
            field=models.ImageField(default='', upload_to='img_users'),
            preserve_default=False,
        ),
    ]
