# Generated by Django 4.2.4 on 2023-08-23 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0003_alter_model_users_options_model_users_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_users',
            name='img',
            field=models.ImageField(blank=True, upload_to='img_users'),
        ),
    ]
