# Generated by Django 4.2.4 on 2023-10-23 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0003_remove_model_users_url_img_model_users_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model_users',
            name='img',
        ),
        migrations.AddField(
            model_name='model_users',
            name='img_url',
            field=models.URLField(default='', max_length=240),
            preserve_default=False,
        ),
    ]
