# Generated by Django 4.2.4 on 2023-10-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0004_remove_model_users_img_model_users_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_users',
            name='img_url',
            field=models.URLField(blank=True, max_length=240),
        ),
    ]
