# Generated by Django 4.2.4 on 2023-08-24 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_categoryes_name_blogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='img',
            field=models.ImageField(blank=True, upload_to='img_blogs'),
        ),
    ]
