# Generated by Django 4.2.4 on 2023-09-08 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogs_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryes',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
