# Generated by Django 4.2.4 on 2023-09-14 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_categoryes_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryes',
            name='amount',
        ),
    ]
