# Generated by Django 4.2.4 on 2023-09-20 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_blogs_content_alter_blogs_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='views',
        ),
    ]
