# Generated by Django 4.2.4 on 2023-09-21 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_blogs_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
