# Generated by Django 4.2.4 on 2023-09-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_reactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='likeblog',
            name='title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
