# Generated by Django 4.2.4 on 2023-09-20 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_reactions', '0002_likeblog_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likeblog',
            name='title',
        ),
    ]
