# Generated by Django 4.2.4 on 2023-09-20 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_reactions', '0003_remove_likeblog_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='likeblog',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
